### ISSUE TITLE
Data extraction

### ISSUE THREAD

**Issue by ruchik-eng** [UM-ARM-Lab/pytorch_kinematics#1]
How do i import the data generated in jacobian into excel.

**Comment by LemonPi** [comment]
Sorry, I don't understand what you mean by "generated in jacobian"? Do you mean you've computed the Jacobian of some configuration and want to import that in some form into excel (so matrix/pytorch tensor into excel spreadsheet)?

**Comment by ruchik-eng** [comment]
Ya i wanted to import it into excel.

**Comment by LemonPi** [comment]
You can do this the same way of converting other tensors to a .csv file which you can open in excel. Take a look at [https://discuss.pytorch.org/t/how-could-i-save-tensor-result-to-a-csv-file/90109](https://discuss.pytorch.org/t/how-could-i-save-tensor-result-to-a-csv-file/90109). There is no special way to do this for Jacobians

**Comment by ruchik-eng** [comment]
Oh thanks for that, i tried excelwriter and it did not work. 
 
  On Wed, May 26, 2021 at 22:01, Johnson ***@***.***> wrote:   


You can do this the same way of converting other tensors to a .csv file which you can open in excel. Take a look at https://discuss.pytorch.org/t/how-could-i-save-tensor-result-to-a-csv-file/90109. There is no special way to do this for Jacobians
