### ISSUE TITLE
What jacobian is computed exactly?

### ISSUE THREAD

**Issue by JonathanKuelz** [UM-ARM-Lab/pytorch_kinematics#34]
Hey, I have short question regarding the Jacobian matrix: Looking through the code, I am still not entirely sure which Jacobian exactly is computed.

In [the second last line](https://github.com/UM-ARM-Lab/pytorch_kinematics/blob/master/src/pytorch_kinematics/jacobian.py#L59) of the implementation the jacobian is "converted" to the world frame. The code before looks like a geometric derivation of this Jacobian. Am I correct assuming the result is the *geometric Jacobian*, expressed in the world frame?

Thanks in advance!

**Comment by powertj** [comment]
Yes, the jacobian calculated is the geometric jacobian in the world frame.
