### ISSUE TITLE
Floating-base Model from SDF?

### ISSUE THREAD

**Issue by alberthli** [UM-ARM-Lab/pytorch_kinematics#37]
I have an SDF of a floating robot hand that I'm trying to load. However, upon creating the `Chain`, I find that there are no states associated with the base of the robot.

I see that the joint types allowed [do not include floating-base joints](https://github.com/UM-ARM-Lab/pytorch_kinematics/blob/dbb641a495afb1abbea24b28d53c3ed89e98f157/src/pytorch_kinematics/frame.py#L45), and the `Chain` also therefore doesn't have this functionality. How big of an effort would it be to add this?

**Comment by LemonPi** [comment]
Hi, for simplicity and consistency all the coordinates are given in robot frame. For a floating-base robot inside of a global world frame, you'll need to manage the world-to-robot and robot-to-world frame transform explicitly.
