### ISSUE TITLE
Version 0.7 on pypi does not import properly

### ISSUE THREAD

**Issue by atommoyer** [UM-ARM-Lab/pytorch_kinematics#38]
```python
>>> import pytorch_kinematics as pk
ModuleNotFoundError: No module named 'arm_pytorch_utilities'
```

**Comment by LemonPi** [comment]
Hi sorry, a fix will be made promptly

**Comment by LemonPi** [comment]
Should be fixed in https://github.com/UM-ARM-Lab/pytorch_kinematics/commit/f6a4d53d5454bb462834daa999f4d6c286ae0ccc (in the latest 0.7.1 release)
