### ISSUE TITLE
How to output tensor array directly instead of transform3d format？

### ISSUE THREAD

**Issue by WangXingfang** [UM-ARM-Lab/pytorch_kinematics#5]
Thank you very much for your work. It gives me great help!
In the process of using the forward kinematics function, I want to output the position of the robot joint directly, rather than an transform3d format.

_ret = chain.forward_kinematics(th_batch, end_only=False)_
_mat = ret.get_matrix()_

I don't want to use the "_get_matrix()_" function, because it will take some time. So how to take "_ret_" as a tensor array which can be used directly.

**Comment by LemonPi** [comment]
To get the positions the full transform has to be computed from its lazy state, which get_matrix() will do. Retrieving the matrix itself should be almost free since we're not making a copy of it. get_matrix() is currently the best way to get the position sensors.
